server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tableorder?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

jwt:
  secret: dGFibGVvcmRlci1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tZ2VuZXJhdGlvbi0yMDI2
  admin-expiration-hours: 16
  table-expiration-hours: 24
